REM  runs script generated by Chahid Taaban
cd C:\Users\Taaban\Desktop\Windows8 bestanden\TU Delft\Bsc3\Semester 2\BEP\Conceptvorming\Collegeweek 3\1DModellen\Grid-model\Bc_1\SwanRuns\40
call swan_run dam_40_RUN001
cd C:\Users\Taaban\Desktop\Windows8 bestanden\TU Delft\Bsc3\Semester 2\BEP\Conceptvorming\Collegeweek 3\1DModellen\Grid-model\Bc_1\SwanRuns\40
call swan_run dam_40_RUN002
cd C:\Users\Taaban\Desktop\Windows8 bestanden\TU Delft\Bsc3\Semester 2\BEP\Conceptvorming\Collegeweek 3\1DModellen\Grid-model\Bc_1\SwanRuns\20
call swan_run dam_20_RUN003
cd C:\Users\Taaban\Desktop\Windows8 bestanden\TU Delft\Bsc3\Semester 2\BEP\Conceptvorming\Collegeweek 3\1DModellen\Grid-model\Bc_1\SwanRuns\20
call swan_run dam_20_RUN004
